<a href="https://colab.research.google.com/github/palleramcharan/Pythonpractice/blob/main/FreeCodeCampPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [170]:
#@title Default title text
import numpy as np

a=np.array([[1,2,3,11,22,33],[4,5,6,44,55,66],[7,8,9,77,88,99]])
print(a)

[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]
 [ 7  8  9 77 88 99]]



shape of an array


In [171]:
a.shape 

(3, 6)

size of an array

In [172]:
a.size

18

Number of Dimentions

In [173]:
a.ndim

2

Indexing & Slicing of Matrices

In [174]:
a[1,3]

44

In [175]:
a[0,2]

3

Replacing the array numbers

In [176]:
a[1]=np.array([10,10,10,11,11,11])
a

array([[ 1,  2,  3, 11, 22, 33],
       [10, 10, 10, 11, 11, 11],
       [ 7,  8,  9, 77, 88, 99]])

In [177]:
a[1]=90
a

array([[ 1,  2,  3, 11, 22, 33],
       [90, 90, 90, 90, 90, 90],
       [ 7,  8,  9, 77, 88, 99]])

In [178]:
a[1]=np.array([4,5,6,44,55,66])

Summary Statistics

In [179]:
print(a)
print(" ") # to make the blank space
print("sum of matrix is : ",a.sum())
print(" ")
print("Standard Deviation of the matrix is : ",a.std())
print(" ")
print("Mean of the matrix is : ",a.mean())

[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]
 [ 7  8  9 77 88 99]]
 
sum of matrix is :  540
 
Standard Deviation of the matrix is :  32.11956828269438
 
Mean of the matrix is :  30.0


In [180]:
c = np.arange(5) #gives the numbers starting from 0
c + 20
c

array([0, 1, 2, 3, 4])

Boolean arrays

In [185]:
print("Array is: ",c)
print(" ")
print("Is the array greater than or equal  2: ",c >= 2)  #gives boolean output
print(" ")
print("Return the numbers less than or equal to 2: ", c[c>=2])
print(" ")
print("Return the numbers greater than mean ie.,", c.mean()," Result : ",c[c>c.mean()])
print(" ")
print("Return the numbers equal to 1 OR 2 : ",c[(c==1) | (c==2)])
print(" ")
print("Return the numbers equal to 1 AND 2 : ",c[(c==1) & (c==2)])

Array is:  [0 1 2 3 4]
 
Is the array greater than or equal  2:  [False False  True  True  True]
 
Return the numbers less than or equal to 2:  [2 3 4]
 
Return the numbers greater than mean ie., 2.0  Result :  [3 4]
 
Return the numbers equal to 1 OR 2 :  [1 2]
 
Return the numbers equal to 1 AND 2 :  []
