#Numpy

In [41]:
#@title Default title text
import numpy as np

a=np.array([[1,2,3,11,22,33],[4,5,6,44,55,66],[7,8,9,77,88,99]])
print(a)

[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]
 [ 7  8  9 77 88 99]]



shape of an array


In [42]:
a.shape 

(3, 6)

size of an array

In [43]:
a.size

18

Number of Dimentions

In [44]:
a.ndim

2

Indexing & Slicing of Matrices

In [45]:
a[1,3]

44

In [46]:
a[0,2]

3

Replacing the array numbers

In [47]:
a[1]=np.array([10,10,10,11,11,11])
a

array([[ 1,  2,  3, 11, 22, 33],
       [10, 10, 10, 11, 11, 11],
       [ 7,  8,  9, 77, 88, 99]])

In [48]:
a[1]=90
a

array([[ 1,  2,  3, 11, 22, 33],
       [90, 90, 90, 90, 90, 90],
       [ 7,  8,  9, 77, 88, 99]])

In [49]:
a[1]=np.array([4,5,6,44,55,66])

Summary Statistics

In [50]:
print(a)
print(" ") # to make the blank space
print("sum of matrix is : ",a.sum())
print(" ")
print("Standard Deviation of the matrix is : ",a.std())
print(" ")
print("Mean of the matrix is : ",a.mean())

[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]
 [ 7  8  9 77 88 99]]
 
sum of matrix is :  540
 
Standard Deviation of the matrix is :  32.11956828269438
 
Mean of the matrix is :  30.0


In [51]:
c = np.arange(5) #gives the numbers starting from 0
c + 20
c

array([0, 1, 2, 3, 4])

Boolean arrays

In [52]:
print("Array is: ",c)
print(" ")
print("Is the array greater than or equal  2: ",c >= 2)  #gives boolean output
print(" ")
print("Return the numbers less than or equal to 2: ", c[c>=2])
print(" ")
print("Return the numbers greater than mean ie.,", c.mean()," Result : ",c[c>c.mean()])
print(" ")
print("Return the numbers equal to 1 OR 2 : ",c[(c==1) | (c==2)])
print(" ")
print("Return the numbers equal to 1 AND 2 : ",c[(c==1) & (c==2)])

Array is:  [0 1 2 3 4]
 
Is the array greater than or equal  2:  [False False  True  True  True]
 
Return the numbers less than or equal to 2:  [2 3 4]
 
Return the numbers greater than mean ie., 2.0  Result :  [3 4]
 
Return the numbers equal to 1 OR 2 :  [1 2]
 
Return the numbers equal to 1 AND 2 :  []


Linear Algebra

In [53]:
d=np.array([[12,14,15,16],[55,34,56,90]])
e=np.array([[78,45,24,56],[90,65,78,99]])
print(d)
print(" ")
print(e)

[[12 14 15 16]
 [55 34 56 90]]
 
[[78 45 24 56]
 [90 65 78 99]]


In [54]:
d*e

array([[ 936,  630,  360,  896],
       [4950, 2210, 4368, 8910]])

#Pandas

Pandas series

In [55]:
import pandas as pd

se=pd.Series([12.22,23.33,34.44,45.55,56.77])
se.name="List of amount"
print(se)
print(" ")
print("The Type of the above series is '", type(se.values),"' and values are",se.values," and size is ",se.size)


0    12.22
1    23.33
2    34.44
3    45.55
4    56.77
Name: List of amount, dtype: float64
 
The Type of the above series is ' <class 'numpy.ndarray'> ' and values are [12.22 23.33 34.44 45.55 56.77]  and size is  5


In [56]:
g7_pop = pd.Series([35.467, 63.951, 80.940, 60.665, 127.061, 64.511, 318.523])
g7_pop=g7_pop*10_00_000
g7_pop.name = 'G7 Population in millions'
g7_pop.index =(['Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States'])
print(g7_pop)
print(" ")
print(" ")
print("Population greater than 80 Million :")
print(" ")
print(g7_pop[g7_pop>=80000000])

Canada             35467000.0
France             63951000.0
Germany            80940000.0
Italy              60665000.0
Japan             127061000.0
United Kingdom     64511000.0
United States     318523000.0
Name: G7 Population in millions, dtype: float64
 
 
Population greater than 80 Million :
 
Germany           80940000.0
Japan            127061000.0
United States    318523000.0
Name: G7 Population in millions, dtype: float64


Dataframes

In [57]:
df=pd.DataFrame({
    "Population":(12.3,45.66,78.54,99.99,12.67,56.56),
    "GDP":(134533,645464,778877,345245,345345,778886),
    "Surface Area":(44556677,23423523,3563463,2342352,236236,235235),
    "MDI":(0.987,0.986,0.252,0.53463,0.232,0.24352),
    "Continent":("Asia","America","Europe","Asia","America","Asia")
})
print(df)
print(" ")
print(df.info())
print(" ")
print("Shape of the DataFrame is : ",df.shape)
print(" ")
print("Size of the DataFrame is : ",df.size)

   Population     GDP  Surface Area      MDI Continent
0       12.30  134533      44556677  0.98700      Asia
1       45.66  645464      23423523  0.98600   America
2       78.54  778877       3563463  0.25200    Europe
3       99.99  345245       2342352  0.53463      Asia
4       12.67  345345        236236  0.23200   America
5       56.56  778886        235235  0.24352      Asia
 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Population    6 non-null      float64
 1   GDP           6 non-null      int64  
 2   Surface Area  6 non-null      int64  
 3   MDI           6 non-null      float64
 4   Continent     6 non-null      object 
dtypes: float64(2), int64(2), object(1)
memory usage: 368.0+ bytes
None
 
Shape of the DataFrame is :  (6, 5)
 
Size of the DataFrame is :  30


Indexing,Selection & Slicing

In [58]:
df.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom'
]

df.loc["Canada"]    #loc is used to get the individual rows

Population          12.3
GDP               134533
Surface Area    44556677
MDI                0.987
Continent           Asia
Name: Canada, dtype: object